# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Kafka Producer using Gradle

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{github.workspace}}
#          cache: gradle
      - name: Build Kafka Producer with Gradle
        run:  gradle build 
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs